In [142]:
import numpy as np
import pandas as pd

In [143]:
group_array = np.load("/work/alanpham/overparam_spur_corr/group_array.npy")
split_array = np.load("/work/alanpham/overparam_spur_corr/split_array.npy")

In [144]:
np.unique(group_array, return_counts=True)

(array([0, 1, 2, 3]), array([89931, 82685, 28234,  1749]))

In [145]:
np.unique(split_array, return_counts=True)

(array([0, 1, 2]), array([162770,  19867,  19962]))

In [146]:
np.sum(np.logical_and(group_array == 3, split_array == 0))

1387

In [147]:
train_and_minority = np.logical_and(group_array == 3, split_array == 0) # train is 0, val is 1, test is 2

In [148]:
get_indices_of_true = lambda t: [i for i, x in enumerate(t) if x]

In [149]:
indices_train_and_minority = np.array(get_indices_of_true(train_and_minority))
num_to_change_to_test = len(indices_train_and_minority) // 2

In [150]:
np.random.seed(0)
indicies_to_change_to_test = indices_train_and_minority[np.random.choice(len(indices_train_and_minority), size=num_to_change_to_test, replace=False)]

In [159]:
from math import floor
floor(len(indices_train_and_minority) * .5)

693

# change

In [151]:
indicies_to_change_to_test[0]

80585

In [152]:
split_array[indicies_to_change_to_test] = 2

In [153]:
np.unique(split_array, return_counts=True)

(array([0, 1, 2]), array([162077,  19867,  20655]))

In [154]:
np.sum(np.logical_and(group_array == 3, split_array == 0))

694

In [155]:
idc = 26888
group_array[idc], split_array[idc]

(3, 0)

In [156]:
np.save("/work/alanpham/overparam_spur_corr/split_array_50p_train_to_test.npy", split_array)